version: '4.17.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=credit_approval_db
      - POSTGRES_USER=postgres
    container_name: db
  django-app:
    build: /app
    ports:
      - "8000:8000"
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

